//! `syschk tasks` — 지원 작업 목록. `--markdown` 은 docs 생성에 쓴다.

use crate::tasks::{MENU, Screen, registry, search};
use crate::tools::registry as tool_registry;

pub fn run(query: Option<&str>, screen: Option<usize>, markdown: bool) -> i32 {
    if markdown {
        return print_markdown();
    }
    if let Some(q) = query {
        let hits = search::find(q);
        if hits.is_empty() {
            println!("nothing matches \"{q}\"");
            return 1;
        }
        println!("{} match(es) for \"{q}\"\n", hits.len());
        for hit in hits {
            println!(
                "  {:>2}. {:<48} {}",
                hit.task.screen.number(),
                hit.task.title,
                hit.task.id
            );
        }
        return 0;
    }

    let screens: Vec<Screen> = match screen {
        Some(n) if (1..=MENU.len()).contains(&n) => vec![MENU[n - 1]],
        Some(n) => {
            eprintln!("screen must be between 1 and {} (got {n})", MENU.len());
            return 2;
        }
        None => MENU.to_vec(),
    };

    let (ready, total) = registry::progress();
    println!("syschk task catalogue - {ready} of {total} working today\n");
    for s in screens {
        println!("{:>2}. {}  [{}]", s.number(), s.title(), s.tag());
        for task in s.tasks() {
            let state = match task.state {
                crate::tasks::TaskState::Ready => "ready  ".to_string(),
                crate::tasks::TaskState::Planned => format!("{:<7}", task.milestone),
            };
            println!("    {state} {}", task.title);
        }
        println!();
    }
    0
}

/// docs/screens.md 의 표를 그대로 생성한다. 문서와 코드가 어긋나지 않게 하려는 목적이다.
fn print_markdown() -> i32 {
    println!("<!-- generated by `syschk tasks --markdown` - do not edit by hand -->");
    for s in MENU {
        println!("\n### {}. {}\n", s.number(), s.title());
        println!("{}\n", s.blurb());
        println!("| Menu item | What you get | Needs | Status |");
        println!("| --- | --- | --- | --- |");
        for task in s.tasks() {
            let needs = if task.tools.is_empty() {
                "-".to_string()
            } else {
                task.tools
                    .iter()
                    .filter_map(|id| tool_registry::by_id(id))
                    .map(|t| format!("`{}`", t.package))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            let state = match task.state {
                crate::tasks::TaskState::Ready => "ready".to_string(),
                crate::tasks::TaskState::Planned => task.milestone.to_string(),
            };
            println!(
                "| {} | {} | {} | {} |",
                task.title, task.answers, needs, state
            );
        }
    }
    0
}
