//! 작업 카탈로그 — 메뉴의 실체.
//!
//! 새 작업을 추가하려면 이 표에 한 항목만 넣는다. 메뉴 표시, 증상 검색, 필요 도구
//! 역참조, 보고서 목차가 모두 여기서 파생된다.
//!
//! `commands` 에 적는 명령은 전부 읽기 전용이어야 한다. `tests/policy.rs` 가
//! 카탈로그 전체를 [`crate::util::exec`] 정책으로 검증한다.

use super::{Screen, Task, TaskState};

macro_rules! t {
    (
        $id:literal, $screen:ident, $ms:literal, $state:ident,
        $title:literal, $answers:literal,
        aka [$($a:literal),* $(,)?],
        needs [$($tool:literal),* $(,)?],
        uses [$($c:literal),* $(,)?]
    ) => {
        Task {
            id: $id,
            screen: Screen::$screen,
            title: $title,
            answers: $answers,
            aliases: &[$($a),*],
            tools: &[$($tool),*],
            commands: &[$($c),*],
            state: TaskState::$state,
            milestone: $ms,
        }
    };
}

static TASKS: &[Task] = &[
    // ══ 1. Live view ══════════════════════════════════════════════
    t!("live.overview", Live, "M1", Planned,
        "Show me everything at a glance",
        "CPU, memory, disk, network and load side by side, each with a plain verdict",
        aka ["dashboard", "overview", "summary", "status", "health"],
        needs ["procps"],
        uses ["cat /proc/loadavg", "free -h", "df -hT", "ip -s link"]),
    t!("live.cpu", Live, "M1", Planned,
        "Who is using the CPU right now",
        "Top processes by CPU, per-core spread, and the user/system/iowait split",
        aka ["cpu", "busy", "load", "100%", "hot"],
        needs ["procps", "sysstat"],
        uses ["ps -eo pid,user,pcpu,pmem,stat,etime,args --sort=-pcpu", "mpstat -P ALL 1 3", "pidstat -u 1 3"]),
    t!("live.memory", Live, "M1", Planned,
        "Who is using memory right now",
        "Top processes by resident memory, cache versus real usage, and whether swap is in play",
        aka ["memory", "ram", "swap", "cache"],
        needs ["procps"],
        uses ["free -h", "ps -eo pid,user,rss,vsz,pmem,args --sort=-rss", "swapon --show", "cat /proc/meminfo"]),
    t!("live.disk-io", Live, "M1", Planned,
        "Who is reading and writing the disk right now",
        "Per-process I/O and per-device queue depth and wait time",
        aka ["io", "disk", "iowait", "slow disk", "writing"],
        needs ["sysstat", "iotop"],
        uses ["iostat -xz 1 5", "pidstat -d 1 3", "iotop -bon1"]),
    t!("live.network", Live, "M1", Planned,
        "Who is using the network right now",
        "Throughput per interface and the spread of connection states",
        aka ["network", "bandwidth", "traffic", "connections"],
        needs ["iproute2"],
        uses ["ip -s link", "ss -s", "ss -tanp"]),
    t!("live.stuck", Live, "M1", Planned,
        "Is any program stuck and not responding",
        "Processes in uninterruptible wait, and what they are waiting on",
        aka ["stuck", "hang", "frozen", "not responding", "d state"],
        needs ["procps"],
        uses ["ps -eo pid,stat,wchan:24,args", "cat /proc/pressure/io"]),
    t!("live.freeze", Live, "M1", Planned,
        "Freeze the screen and look closer",
        "Pause updates, re-sort, and pin one process to watch",
        aka ["pause", "freeze", "sort", "pin"],
        needs [],
        uses []),
    // ══ 2. Something is slow ══════════════════════════════════════
    t!("slow.verdict", Slow, "M1", Planned,
        "Just tell me what is making it slow",
        "One of cpu / memory / disk / network named as the bottleneck, with the numbers behind it",
        aka ["slow", "sluggish", "lag", "laggy", "unresponsive", "why slow"],
        needs ["procps", "sysstat"],
        uses ["cat /proc/pressure/cpu", "cat /proc/pressure/memory", "cat /proc/pressure/io", "vmstat 1 5"]),
    t!("slow.cpu", Slow, "M1", Planned,
        "Am I running out of CPU",
        "Load against core count, run-queue length, steal time on virtual machines, and throttling",
        aka ["cpu bound", "load average", "steal", "throttle", "frequency"],
        needs ["procps", "sysstat", "linux-cpupower"],
        uses ["cat /proc/loadavg", "mpstat -P ALL 1 3", "cpupower frequency-info"]),
    t!("slow.memory", Slow, "M1", Planned,
        "Am I running out of memory",
        "Free versus cache, swap trend, page reclaim pressure, and any past OOM kill",
        aka ["out of memory", "oom", "swapping", "thrashing", "memory pressure"],
        needs ["procps"],
        uses ["free -h", "cat /proc/pressure/memory", "vmstat 1 5", "journalctl -k --grep oom"]),
    t!("slow.disk", Slow, "M1", Planned,
        "Is the disk too slow",
        "Per-device latency, queue and utilisation, iowait share, and who is waiting",
        aka ["disk slow", "iowait", "latency", "queue"],
        needs ["sysstat"],
        uses ["iostat -xz 1 5", "cat /proc/pressure/io", "sar -d -p"]),
    t!("slow.culprit", Slow, "M1", Planned,
        "Is one program to blame",
        "The heaviest consumers on each axis, with a jump into per-process detail",
        aka ["which process", "culprit", "hog", "eating cpu"],
        needs ["procps"],
        uses ["ps -eo pid,user,pcpu,pmem,rss,args --sort=-pcpu", "pidstat -urd 1 3"]),
    t!("slow.compare-past", Slow, "M3", Planned,
        "Was it always like this - compare with the past",
        "The same figures over recent days, so 'slow' can be measured against normal",
        aka ["history", "trend", "yesterday", "before", "compare"],
        needs ["sysstat"],
        uses ["sar -u", "sar -r", "sar -b"]),
    t!("slow.containers", Slow, "M6", Planned,
        "Is a container eating the resources",
        "CPU, memory and I/O per container against its configured limit",
        aka ["docker", "container", "cgroup", "podman", "limit"],
        needs ["docker"],
        uses ["docker stats --no-stream", "systemd-cgtop -n 1 -b"]),
    // ══ 3. It froze or rebooted ═══════════════════════════════════
    t!("halt.when", Halt, "M3", Planned,
        "When did it stop",
        "Boot sessions listed, with the last healthy record and the restart time bracketing the stop",
        aka ["froze", "frozen", "hung", "crashed", "rebooted", "power cycle", "when"],
        needs ["systemd", "sysstat"],
        uses ["journalctl --list-boots", "uptime -s", "last"]),
    t!("halt.clean-or-hard", Halt, "M3", Planned,
        "Was it a clean shutdown or a hard stop",
        "Whether the previous session ended with normal shutdown records or was cut off mid-line",
        aka ["clean shutdown", "hard reset", "power loss", "unexpected"],
        needs ["systemd"],
        uses ["journalctl -b -1", "journalctl --list-boots"]),
    t!("halt.kernel-messages", Halt, "M3", Planned,
        "Did the kernel leave anything behind",
        "Kernel-only messages scanned for the known failure patterns, noise filtered out",
        aka ["kernel panic", "oops", "call trace", "lockup", "xid", "mce"],
        needs ["systemd", "util-linux"],
        uses ["journalctl -b -1 -k", "journalctl -k --grep oom", "dmesg -T", "dmesg -l err,crit,alert,emerg"]),
    t!("halt.resources", Halt, "M3", Planned,
        "Did it run out of resources",
        "Recorded CPU, load, memory, swap and I/O right before the stop, each ruled in or out",
        aka ["resource exhaustion", "oom", "swap", "iowait", "before crash"],
        needs ["sysstat"],
        uses ["sar -q", "sar -r", "sar -S", "sar -b"]),
    t!("halt.hardware", Halt, "M6", Planned,
        "Was it a hardware problem",
        "Drive health, memory error counters, temperatures and link state at a glance",
        aka ["hardware failure", "ecc", "overheat", "psu", "power"],
        needs ["smartmontools", "rasdaemon", "lm-sensors"],
        uses ["smartctl -H /dev/sda", "cat /sys/devices/system/edac/mc/mc0/ce_count", "ras-mc-ctl --summary", "sensors"]),
    t!("halt.crash-record", Halt, "M3", Planned,
        "Is there a kernel crash record",
        "Crash dumps, firmware-stored panic logs and core dumps, if any exist",
        aka ["crash dump", "kdump", "pstore", "panic log", "vmcore"],
        needs ["systemd", "kdump-tools"],
        uses ["ls /var/crash", "ls /sys/fs/pstore", "coredumpctl list", "kdump-config show"]),
    t!("halt.killed", Halt, "M3", Planned,
        "Was my program killed",
        "OOM kill targets, units that exited with a failure code, and core dump history",
        aka ["killed", "oom killer", "sigkill", "exit code", "died"],
        needs ["systemd"],
        uses ["journalctl -k --grep oom-kill", "systemctl list-units --state=failed", "coredumpctl list"]),
    t!("halt.conclusion", Halt, "M3", Planned,
        "Summarise the conclusion",
        "Causes sorted into ruled out / weakened / likely / undetermined, each with its evidence",
        aka ["conclusion", "summary", "cause", "root cause", "verdict"],
        needs [],
        uses []),
    t!("halt.next-steps", Halt, "M3", Planned,
        "What should I check next",
        "For each remaining cause, the least invasive way to confirm or drop it",
        aka ["next", "what now", "how to confirm"],
        needs [],
        uses []),
    // ══ 4. Storage ════════════════════════════════════════════════
    t!("storage.which-full", Storage, "M2", Planned,
        "Which filesystem is full",
        "Usage and free space per mount point, with the ones over threshold called out",
        aka ["disk full", "no space", "full", "df", "space"],
        needs ["util-linux"],
        uses ["df -hT", "df -i", "findmnt -D"]),
    t!("storage.what-fills", Storage, "M2", Planned,
        "Find what is filling up the disk",
        "Largest directories, with drill-down into subdirectories",
        aka ["large files", "biggest", "du", "what is using space"],
        needs [],
        uses ["du -xh --max-depth=1 /", "find / -xdev -size +1G -type f"]),
    t!("storage.deleted-held", Storage, "M2", Planned,
        "I deleted files but the space did not come back",
        "Files that are unlinked but still open, and the processes holding them",
        aka ["deleted", "space not freed", "still full after delete", "held open"],
        needs ["lsof"],
        uses ["lsof +L1"]),
    t!("storage.inodes", Storage, "M2", Planned,
        "There is free space but I get 'No space left'",
        "Inode exhaustion, reserved blocks and quota limits - the three usual explanations",
        aka ["no space left", "inode", "quota", "reserved blocks"],
        needs ["util-linux", "e2fsprogs"],
        uses ["df -i", "tune2fs -l /dev/sda1", "repquota -a"]),
    t!("storage.logs", Storage, "M2", Planned,
        "Are logs eating the space",
        "Journal footprint, largest log directories and whether rotation is configured",
        aka ["logs", "journal", "var log", "log rotation"],
        needs ["systemd"],
        uses ["journalctl --disk-usage", "du -sh /var/log", "logrotate -d /etc/logrotate.conf"]),
    t!("storage.drive-failing", Storage, "M2", Planned,
        "Is the drive failing",
        "SMART health plus the attributes that actually predict failure, and NVMe wear and temperature",
        aka ["failing disk", "smart", "bad sectors", "disk dying", "reallocated"],
        needs ["smartmontools", "nvme-cli"],
        uses ["smartctl -H /dev/sda", "smartctl -A /dev/sda", "smartctl -l error /dev/sda", "nvme smart-log /dev/nvme0"]),
    t!("storage.errors", Storage, "M2", Planned,
        "Are there disk error records",
        "Storage-related kernel errors: link resets, I/O errors and filesystem errors",
        aka ["io error", "ata error", "reset", "ext4 error", "read only filesystem"],
        needs ["systemd"],
        uses ["journalctl -k --grep \"I/O error\"", "dmesg -T"]),
    t!("storage.layout", Storage, "M2", Planned,
        "Show me how the disks are laid out",
        "Devices, partitions, filesystems and mounts as a tree, plus RAID and LVM state",
        aka ["layout", "partitions", "lsblk", "raid", "lvm", "mounts"],
        needs ["util-linux", "lvm2", "mdadm"],
        uses ["lsblk -o NAME,SIZE,TYPE,ROTA,FSTYPE,MOUNTPOINT,MODEL", "cat /proc/mdstat", "lvs -a", "vgs"]),
    t!("storage.fs-health", Storage, "M2", Planned,
        "Is the filesystem healthy",
        "Mount options, read-only fallback, check-needed flags and superblock state",
        aka ["filesystem", "read only", "fsck", "corrupt", "ext4"],
        needs ["e2fsprogs", "util-linux"],
        uses ["findmnt -o TARGET,OPTIONS", "tune2fs -l /dev/sda1", "dumpe2fs -h /dev/sda1", "fsck -N /dev/sda1"]),
    // ══ 5. Network ════════════════════════════════════════════════
    t!("network.where-breaks", Network, "M5", Planned,
        "Tell me where the connection breaks",
        "Link, address, gateway, internet, DNS and HTTPS checked in order, stopping at the first failure",
        aka ["no internet", "cannot connect", "network down", "offline", "unreachable"],
        needs ["iproute2", "iputils", "dnsutils", "curl"],
        uses ["ip -br a", "ip r", "ping -c4 1.1.1.1", "dig openai.com", "curl -sS -o /dev/null -w %{http_code} https://ubuntu.com"]),
    t!("network.my-config", Network, "M5", Planned,
        "What is my IP, gateway and DNS",
        "Interface addresses, the routing table, and the name servers actually in use",
        aka ["ip address", "gateway", "dns", "resolv.conf", "netplan"],
        needs ["iproute2"],
        uses ["ip -br a", "ip r", "resolvectl status", "cat /etc/resolv.conf"]),
    t!("network.listening", Network, "M5", Planned,
        "Which ports are open and who is listening",
        "Listening sockets with owning process, separating localhost-only from externally reachable",
        aka ["ports", "listening", "open port", "bind", "who is listening"],
        needs ["iproute2"],
        uses ["ss -tulpn"]),
    t!("network.reach-host", Network, "M5", Planned,
        "Can I reach a specific host or port",
        "Reachability for a host and port you choose, naming the step that fails",
        aka ["cannot reach", "connection refused", "timeout", "port closed"],
        needs ["iputils", "netcat", "dnsutils"],
        uses ["ping -c4 HOST", "nc -zv HOST PORT", "dig HOST"]),
    t!("network.dns", Network, "M5", Planned,
        "Is name resolution the problem",
        "Query results and response time per configured name server",
        aka ["dns", "name resolution", "cannot resolve", "nxdomain", "slow dns"],
        needs ["dnsutils"],
        uses ["resolvectl query ubuntu.com", "dig ubuntu.com", "dig @1.1.1.1 ubuntu.com"]),
    t!("network.path", Network, "M5", Planned,
        "Where does the delay or packet loss happen",
        "Per-hop latency and loss along the path",
        aka ["packet loss", "latency", "traceroute", "hops", "jitter"],
        needs ["mtr", "traceroute"],
        uses ["mtr -rwc10 1.1.1.1", "traceroute 1.1.1.1"]),
    t!("network.slow", Network, "M5", Planned,
        "Why is the network slow",
        "Throughput, retransmits, errors and drops, negotiated link speed and MTU",
        aka ["slow network", "throughput", "retransmit", "drops", "mtu", "duplex"],
        needs ["ethtool", "sysstat", "iproute2"],
        uses ["sar -n DEV", "sar -n EDEV", "ethtool eth0", "ip -s link"]),
    t!("network.firewall", Network, "M5", Planned,
        "Is the firewall blocking it",
        "Whether a firewall is active, a summary of its rules, and any related block records",
        aka ["firewall", "ufw", "iptables", "nftables", "blocked"],
        needs [],
        uses ["ufw status verbose", "nft list ruleset", "iptables -L -n -v"]),
    t!("network.too-many-conns", Network, "M5", Planned,
        "Are there too many connections",
        "Connection counts by state against socket and connection-tracking limits",
        aka ["too many connections", "conntrack", "time wait", "socket limit"],
        needs ["iproute2"],
        uses ["ss -s", "sysctl net.netfilter.nf_conntrack_count", "sysctl net.netfilter.nf_conntrack_max"]),
    t!("network.packets", Network, "M5", Planned,
        "Let me look at the actual packets",
        "A short, bounded capture with a summary - after confirming the added load",
        aka ["packet capture", "tcpdump", "sniff", "pcap"],
        needs ["tcpdump"],
        uses ["tcpdump -nn -c 200"]),
    // ══ 6. Services and boot ══════════════════════════════════════
    t!("services.failed", Services, "M4", Planned,
        "Which services failed",
        "Failed units with exit codes and their last log lines",
        aka ["service failed", "unit failed", "not running", "dead", "systemctl"],
        needs ["systemd"],
        uses ["systemctl --failed", "systemctl list-units --state=failed", "systemctl is-system-running"]),
    t!("services.why-not-start", Services, "M4", Planned,
        "Why does this service not start",
        "State, dependencies, recent logs, effective configuration and restart count in one place",
        aka ["will not start", "start failed", "crash loop", "exited"],
        needs ["systemd"],
        uses ["systemctl status UNIT", "systemctl cat UNIT", "systemctl list-dependencies UNIT", "journalctl -u UNIT -b"]),
    t!("services.autostart", Services, "M4", Planned,
        "Is this service set to start on boot",
        "Enabled, disabled or masked, plus the configuration files actually in effect",
        aka ["enabled", "autostart", "on boot", "masked"],
        needs ["systemd"],
        uses ["systemctl is-enabled UNIT", "systemctl list-unit-files --state=enabled", "systemctl cat UNIT"]),
    t!("services.slow-boot", Services, "M4", Planned,
        "Why is boot slow",
        "Total boot time broken down, the slowest units, and the critical path",
        aka ["slow boot", "startup", "boot time", "takes long to start"],
        needs ["systemd"],
        uses ["systemd-analyze", "systemd-analyze blame", "systemd-analyze critical-chain"]),
    t!("services.timers", Services, "M4", Planned,
        "Are scheduled jobs running",
        "Timers with last and next run, cron jobs, and their execution logs",
        aka ["cron", "timer", "scheduled", "not running on schedule", "backup job"],
        needs ["systemd"],
        uses ["systemctl list-timers --all", "crontab -l", "journalctl -u cron"]),
    t!("services.resources", Services, "M4", Planned,
        "How much does this service use",
        "CPU and memory per unit against the limits set for it",
        aka ["service memory", "unit cpu", "cgroup limit", "memorymax"],
        needs ["systemd"],
        uses ["systemd-cgtop -n 1 -b", "systemctl show UNIT"]),
    t!("services.restart-loop", Services, "M4", Planned,
        "Is it restarting over and over",
        "Restart counters, the interval between restarts, and the surrounding log window",
        aka ["restart loop", "flapping", "keeps restarting", "crash loop"],
        needs ["systemd"],
        uses ["systemctl show UNIT", "journalctl -u UNIT -b"]),
    // ══ 7. One program ════════════════════════════════════════════
    t!("process.what-doing", Process, "M4", Planned,
        "What is this program doing",
        "State, command line, parent and children, and the unit or container it belongs to",
        aka ["process", "pid", "what is this", "program"],
        needs ["procps", "psmisc"],
        uses ["ps -eo pid,ppid,user,stat,pcpu,pmem,etime,args", "pstree -paul", "cat /proc/PID/status"]),
    t!("process.usage", Process, "M4", Planned,
        "How much does it use",
        "CPU and memory over time, bytes read and written, thread count",
        aka ["process cpu", "process memory", "rss", "threads"],
        needs ["sysstat"],
        uses ["pidstat -urd -p PID 1 5", "cat /proc/PID/io", "pmap -X PID"]),
    t!("process.open-files", Process, "M4", Planned,
        "Which files does it have open",
        "Open files and sockets, including deleted files it still holds",
        aka ["open files", "fd", "sockets", "file descriptors", "too many open files"],
        needs ["lsof"],
        uses ["lsof -p PID", "ls /proc/PID/fd"]),
    t!("process.limits", Process, "M4", Planned,
        "Which limits is it hitting",
        "File descriptor, memory and task limits against current usage",
        aka ["ulimit", "limit", "nofile", "too many", "resource limit"],
        needs [],
        uses ["cat /proc/PID/limits", "prlimit -p PID", "sysctl fs.file-nr"]),
    t!("process.stuck", Process, "M4", Planned,
        "Why is it stuck",
        "Wait state and kernel wait point, with the likely blocking cause",
        aka ["stuck", "hung", "not responding", "d state", "blocked", "deadlock"],
        needs ["procps", "strace"],
        uses ["cat /proc/PID/status", "cat /proc/PID/wchan", "cat /proc/PID/stack", "strace -f -p PID -c"]),
    t!("process.memory-growth", Process, "M4", Planned,
        "Is it leaking memory",
        "Usage growth over time and how the memory is mapped",
        aka ["memory leak", "growing", "leak", "rss growing"],
        needs ["procps", "smem"],
        uses ["cat /proc/PID/smaps_rollup", "pmap -X PID", "smem -tk"]),
    t!("process.syscalls", Process, "M4", Planned,
        "What calls is it making",
        "A short syscall sample with the slowest calls summarised",
        aka ["strace", "syscall", "what is it doing", "trace"],
        needs ["strace"],
        uses ["strace -f -p PID -c"]),
    // ══ 8. Hardware ═══════════════════════════════════════════════
    t!("hardware.inventory", Hardware, "M6", Planned,
        "What is this machine made of",
        "CPU, memory layout, board, firmware and populated slots",
        aka ["specs", "hardware", "inventory", "cpu model", "how much ram"],
        needs ["dmidecode", "lshw"],
        uses ["lscpu", "lsmem", "dmidecode -t system -t baseboard -t bios", "lshw -short"]),
    t!("hardware.memory-errors", Hardware, "M6", Planned,
        "Are there memory errors",
        "ECC mode in use, corrected and uncorrected error counts, and hardware error records",
        aka ["ecc", "memory error", "ram error", "bad ram", "mce"],
        needs ["rasdaemon"],
        uses ["cat /sys/devices/system/edac/mc/mc0/ce_count", "cat /sys/devices/system/edac/mc/mc0/ue_count", "ras-mc-ctl --summary", "journalctl -k --grep EDAC"]),
    t!("hardware.temperature", Hardware, "M6", Planned,
        "Are the temperatures fine",
        "Temperatures from drivers that can be trusted. Unverified sensors are shown as unavailable, not guessed",
        aka ["temperature", "hot", "overheat", "fan", "thermal", "cooling"],
        needs ["lm-sensors"],
        uses ["sensors", "cat /sys/class/thermal/thermal_zone0/temp"]),
    t!("hardware.cpu-speed", Hardware, "M6", Planned,
        "Is the CPU running at full speed",
        "Current and maximum frequency, throttle reasons and the active power policy",
        aka ["throttle", "frequency", "slow cpu", "governor", "powersave"],
        needs ["linux-cpupower"],
        uses ["cpupower frequency-info", "cat /proc/cpuinfo"]),
    t!("hardware.gpu", Hardware, "M6", Planned,
        "How are the GPUs doing",
        "Power against limit, temperature, throttle reasons, memory errors and link speed, with mismatches between identical cards flagged",
        aka ["gpu", "nvidia", "cuda", "vram", "graphics card"],
        needs ["nvidia-utils"],
        uses ["nvidia-smi", "nvidia-smi --query-gpu=index,name,power.draw,power.limit,temperature.gpu,pcie.link.gen.current,pcie.link.gen.max --format=csv", "nvidia-smi -q"]),
    t!("hardware.expansion", Hardware, "M6", Planned,
        "Are the expansion cards linked properly",
        "PCIe and USB device tree with current versus maximum link speed and width",
        aka ["pcie", "lspci", "usb", "card not detected", "link speed"],
        needs ["pciutils", "usbutils"],
        uses ["lspci -nnk", "lspci -tv", "lsusb -t"]),
    t!("hardware.power", Hardware, "M6", Planned,
        "Can I see the power draw",
        "Whether any power telemetry exists at all - and if not, that fact plus the alternatives",
        aka ["power", "psu", "watts", "power supply", "voltage"],
        needs ["dmidecode", "ipmitool"],
        uses ["dmidecode -t 39", "ipmitool sdr", "ls /dev/ipmi0"]),
    t!("hardware.virtual", Hardware, "M6", Planned,
        "Is this a virtual machine",
        "Whether this runs on bare metal or a hypervisor, and which one",
        aka ["vm", "virtual", "kvm", "hypervisor", "cloud"],
        needs ["systemd"],
        uses ["systemd-detect-virt", "dmidecode -t system"]),
    // ══ 9. Logins and exposure ════════════════════════════════════
    t!("security.who-now", Security, "M6", Planned,
        "Who is logged in right now",
        "Active login sessions, where they came from, and what they are running",
        aka ["who", "logged in", "sessions", "someone else"],
        needs ["systemd"],
        uses ["who -a", "w", "loginctl list-sessions"]),
    t!("security.recent-logins", Security, "M6", Planned,
        "Who logged in recently",
        "Login history with failures, and the source addresses that appear most",
        aka ["login history", "last", "who logged in", "access log"],
        needs [],
        uses ["last -a -n50", "lastb -n50", "journalctl -u ssh"]),
    t!("security.failed-logins", Security, "M6", Planned,
        "Are there floods of failed logins",
        "Authentication failure trend, the accounts targeted, and whether blocking is active",
        aka ["brute force", "failed password", "attack", "ssh attempts", "fail2ban"],
        needs ["fail2ban"],
        uses ["journalctl -u ssh --grep \"Failed password\"", "lastb -n50", "fail2ban-client status"]),
    t!("security.exposure", Security, "M6", Planned,
        "What is exposed to the outside",
        "Externally bound listening ports with their owning process, checked against firewall policy",
        aka ["exposed", "public port", "open to internet", "attack surface"],
        needs ["iproute2"],
        uses ["ss -tulpn", "ufw status numbered"]),
    t!("security.accounts", Security, "M6", Planned,
        "Are the account permissions sane",
        "Administrator accounts, passwordless accounts, expiry policy and remote access settings",
        aka ["accounts", "sudo", "users", "permissions", "root login"],
        needs [],
        uses ["getent passwd", "getent group sudo", "passwd -S -a", "sshd -T"]),
    t!("security.access-control", Security, "M6", Planned,
        "Is access control enabled",
        "AppArmor profile state and recent denials",
        aka ["apparmor", "selinux", "denied", "access control", "confined"],
        needs [],
        uses ["aa-status", "journalctl --grep DENIED"]),
    t!("security.admin-history", Security, "M6", Planned,
        "Show me administrator command history",
        "Privilege escalation records in time order",
        aka ["sudo history", "admin commands", "who ran what", "audit"],
        needs ["systemd"],
        uses ["journalctl --grep sudo:"]),
    // ══ 10. Updates and packages ══════════════════════════════════
    t!("updates.pending", Updates, "M6", Planned,
        "Is there anything to update",
        "How many packages can be upgraded, and which of those are security updates",
        aka ["updates", "upgrade", "apt", "patches", "security update"],
        needs [],
        uses ["apt list --upgradable", "apt-get -s dist-upgrade"]),
    t!("updates.reboot-needed", Updates, "M6", Planned,
        "Do I need to reboot",
        "Whether a reboot is pending, which packages want it, and which services still need restarting",
        aka ["reboot required", "restart needed", "kernel update", "reboot"],
        needs ["needrestart"],
        uses ["cat /var/run/reboot-required", "cat /var/run/reboot-required.pkgs", "needrestart -r l"]),
    t!("updates.automatic", Updates, "M6", Planned,
        "Are automatic updates working",
        "Recent unattended upgrade runs and whether any failed",
        aka ["unattended upgrades", "automatic updates", "auto update"],
        needs ["systemd"],
        uses ["systemctl status unattended-upgrades", "unattended-upgrade --dry-run", "cat /var/log/unattended-upgrades/unattended-upgrades.log"]),
    t!("updates.broken", Updates, "M6", Planned,
        "Are any packages broken",
        "Half-configured packages, dependency problems and packages held back",
        aka ["broken packages", "dpkg error", "half configured", "held back", "apt error"],
        needs [],
        uses ["dpkg --audit", "dpkg -l", "apt-mark showhold", "apt-get -s check"]),
    t!("updates.recent-changes", Updates, "M6", Planned,
        "What changed recently",
        "Install, upgrade and removal history in time order - to line up against when trouble started",
        aka ["what changed", "recent install", "dpkg log", "apt history", "after update"],
        needs [],
        uses ["cat /var/log/dpkg.log", "cat /var/log/apt/history.log"]),
    t!("updates.file-owner", Updates, "M6", Planned,
        "Which package owns this file",
        "File to package, and package to file listing",
        aka ["which package", "dpkg -S", "file owner", "where from"],
        needs ["apt-file"],
        uses ["dpkg -S /usr/bin/ls", "dpkg -L coreutils", "apt-file search FILE"]),
    t!("updates.snaps", Updates, "M6", Planned,
        "How are snaps doing",
        "Installed snaps, recent changes and pending refreshes",
        aka ["snap", "snapd", "snap refresh"],
        needs ["snapd"],
        uses ["snap list --all", "snap changes", "snap refresh --list"]),
    // ══ 11. Logs ══════════════════════════════════════════════════
    t!("logs.around-time", Logs, "M3", Planned,
        "Show me what happened around a certain time",
        "Log entries for a time window you pick, navigable by boot session",
        aka ["logs", "around time", "last night", "what happened", "journalctl"],
        needs ["systemd"],
        uses ["journalctl --since -1h", "journalctl --list-boots", "journalctl -b -1"]),
    t!("logs.one-service", Logs, "M3", Planned,
        "Show me only this service's log",
        "Entries filtered to one unit, with priority filter and live follow",
        aka ["service log", "unit log", "follow", "tail log"],
        needs ["systemd"],
        uses ["journalctl -u UNIT -b", "journalctl -u UNIT -p err"]),
    t!("logs.errors-only", Logs, "M3", Planned,
        "Show me only errors",
        "Severity-filtered entries, with kernel messages viewable on their own",
        aka ["errors", "warnings", "critical", "priority"],
        needs ["systemd"],
        uses ["journalctl -p err..alert", "journalctl -k -p warning"]),
    t!("logs.hide-noise", Logs, "M3", Planned,
        "Hide the repeating noise",
        "High-frequency repeated messages collapsed into counts, with known noise sources toggleable",
        aka ["noise", "spam", "repeating", "flooding logs"],
        needs ["systemd"],
        uses ["journalctl -b"]),
    t!("logs.search", Logs, "M3", Planned,
        "Search for a specific string",
        "Regex search plus ready-made patterns for common failures",
        aka ["search logs", "grep", "find in logs", "pattern"],
        needs ["systemd"],
        uses ["journalctl --grep PATTERN", "journalctl -k --grep PATTERN"]),
    t!("logs.retention", Logs, "M3", Planned,
        "How far back do the logs go",
        "Retention window, disk footprint and integrity of the journal",
        aka ["log retention", "how long", "journal size", "log rotation"],
        needs ["systemd"],
        uses ["journalctl --disk-usage", "journalctl --verify", "cat /etc/systemd/journald.conf"]),
    t!("logs.plain-files", Logs, "M3", Planned,
        "Include the plain log files too",
        "Traditional log files read alongside the journal, with timestamp format differences absorbed",
        aka ["syslog", "kern.log", "auth.log", "var log files"],
        needs [],
        uses ["cat /var/log/syslog", "cat /var/log/kern.log", "cat /var/log/auth.log"]),
    t!("logs.keep", Logs, "M7", Planned,
        "Keep the part I found",
        "The selected range attached to a report or saved to a file",
        aka ["save logs", "export", "keep", "attach"],
        needs [],
        uses []),
    // ══ 12. Readiness ═════════════════════════════════════════════
    t!("readiness.check", Readiness, "M7", Planned,
        "Am I ready to capture the cause",
        "A checklist: crash dump, panic policy, hang detection, hardware error daemon, performance history, core dumps",
        aka ["readiness", "prepare", "next time", "capture cause", "kdump"],
        needs ["kdump-tools", "rasdaemon", "sysstat"],
        uses ["systemctl is-enabled kdump-tools", "sysctl kernel.panic_on_oops", "sysctl kernel.hung_task_timeout_secs", "ls /sys/fs/pstore", "systemctl status rasdaemon"]),
    t!("readiness.how-to-setup", Readiness, "M7", Planned,
        "How do I set up what is missing",
        "For each gap, the exact command or configuration file content - shown, never run",
        aka ["setup", "how to enable", "configure", "fix readiness"],
        needs [],
        uses []),
    t!("readiness.history-granularity", Readiness, "M7", Planned,
        "The performance history is too coarse",
        "The current sampling interval, how much it can miss, and how to change it",
        aka ["sampling", "interval", "10 minutes", "granularity", "sysstat"],
        needs ["sysstat"],
        uses ["cat /etc/cron.d/sysstat", "cat /etc/default/sysstat", "systemctl status sysstat"]),
    t!("readiness.post-mortem-logs", Readiness, "M7", Planned,
        "How do I keep logs after a kernel death",
        "What it takes to keep evidence when the kernel dies mid-write, and what this machine can support",
        aka ["netconsole", "serial console", "remote logging", "kernel dies"],
        needs [],
        uses ["ls /sys/fs/pstore", "cat /proc/cmdline"]),
    t!("readiness.record-now", Readiness, "M7", Planned,
        "Start recording metrics from now on",
        "Chosen metrics written to a file at a fixed interval, for when the problem is intermittent",
        aka ["record", "monitor", "log metrics", "intermittent"],
        needs [],
        uses []),
    // ══ 13. Report ════════════════════════════════════════════════
    t!("report.current-screen", Report, "M7", Planned,
        "Save the current screen",
        "This screen's data, verdicts and the commands behind them, as Markdown",
        aka ["save", "export", "markdown", "screenshot"],
        needs [],
        uses []),
    t!("report.session", Report, "M7", Planned,
        "Save the whole diagnosis session",
        "Everything done in this session in time order: timeline, evidence and how each cause was classified",
        aka ["report", "session", "document", "write up", "record"],
        needs [],
        uses []),
    t!("report.shareable", Report, "M7", Planned,
        "Make it safe to share",
        "The same report with hostnames, addresses and account names masked",
        aka ["share", "mask", "anonymise", "redact", "send to support"],
        needs [],
        uses []),
    t!("report.machine-readable", Report, "M7", Planned,
        "Give me machine-readable output",
        "The same findings as JSON, for other tools to consume",
        aka ["json", "machine readable", "api", "script"],
        needs [],
        uses []),
    t!("report.scheduled", Report, "M7", Planned,
        "Run checks on a schedule",
        "How to run syschk without the interface, and what its exit codes mean",
        aka ["cron", "schedule", "automate", "exit code", "non interactive"],
        needs [],
        uses []),
    // ══ 14. Tools ═════════════════════════════════════════════════
    t!("tools.inventory", Tools, "M0", Ready,
        "What is installed and what is missing",
        "Every tool syschk can use, with its state: installed, missing, or not applicable here",
        aka ["tools", "installed", "missing", "requirements", "dependencies"],
        needs [],
        uses []),
    t!("tools.what-is-it", Tools, "M0", Ready,
        "What does this tool do",
        "A one-line purpose, plus the list of tasks that stop working without it",
        aka ["what is", "purpose", "why do i need", "explain tool"],
        needs [],
        uses []),
    t!("tools.needed-for-task", Tools, "M0", Ready,
        "What do I need for what I am about to do",
        "Only the tools missing for the task you picked, nothing else",
        aka ["what do i need", "prerequisites", "for this task"],
        needs [],
        uses []),
    t!("tools.how-to-install", Tools, "M0", Ready,
        "How do I install it",
        "The package name and the exact install command, shown for you to run. syschk does not install anything itself",
        aka ["install", "apt install", "how to install", "setup tool"],
        needs [],
        uses []),
    t!("tools.bundles", Tools, "M0", Ready,
        "Install a recommended bundle",
        "Grouped install commands: core, storage, network, hardware, diagnostics, advanced",
        aka ["bundle", "install all", "recommended", "group"],
        needs [],
        uses []),
    t!("tools.install-fails", Tools, "M8", Planned,
        "Installation fails - what now",
        "The usual causes (no privileges, no network, stale package index) and what to do about each",
        aka ["install failed", "apt error", "cannot install", "no network"],
        needs [],
        uses []),
    t!("tools.without-installing", Tools, "M0", Ready,
        "What can I do without installing anything",
        "Which checks work from /proc and /sys alone, and where precision is lost",
        aka ["no install", "offline", "without tools", "fallback", "read only"],
        needs [],
        uses []),
];

pub fn tasks() -> &'static [Task] {
    TASKS
}

pub fn by_id(id: &str) -> Option<&'static Task> {
    TASKS.iter().find(|t| t.id == id)
}

/// 지금 동작하는 작업 수와 전체 작업 수.
pub fn progress() -> (usize, usize) {
    let ready = TASKS.iter().filter(|t| t.state == TaskState::Ready).count();
    (ready, TASKS.len())
}
